In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("Car1.csv",na_values=['?','UNDEFINED'])

In [3]:
data

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,selling_price
0,Maruti Swift Dzire VDI,2014,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,450000
1,Skoda Rapid 1.5 TDI Ambition,2014,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0,370000
2,Honda City 2017-2020 EXi,2006,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0,158000
3,Hyundai i20 Sportz Diesel,2010,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0,225000
4,Maruti Swift VXI BSIII,2007,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0,130000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,Maruti Zen Estilo LXI BSIII,2009,55500,Petrol,Dealer,Manual,First Owner,18.2 kmpl,998 CC,67.1 bhp,90Nm@ 3500rpm,5.0,175000
95,Hyundai i20 Asta Optional with Sunroof 1.2,2013,61500,Petrol,Dealer,Manual,First Owner,18.5 kmpl,1197 CC,82.85 bhp,113.7Nm@ 4000rpm,5.0,525000
96,Maruti Swift Dzire LDI,2016,150000,Diesel,Individual,Manual,First Owner,26.59 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,600000
97,Hyundai Xcent 1.2 Kappa SX Option AT,2016,72000,Petrol,Dealer,Automatic,First Owner,19.1 kmpl,1197 CC,82 bhp,114Nm@ 4000rpm,5.0,565000
98,Maruti Alto LX BSIII,2008,68000,Petrol,Dealer,Manual,Third Owner,19.7 kmpl,796 CC,46.3 bhp,62Nm@ 3000rpm,5.0,120000

In [4]:
data.isnull()

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,selling_price
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,False,False,False,False,False,False,False,False,False,False,False,False,False
95,False,False,False,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False,False,False,False,False,False

In [5]:
find=data.isnull().any(axis=1)
data[find]

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,selling_price
13,Maruti Swift 1.3 VXi,2007,80000,Petrol,Individual,Manual,Second Owner,NaN,NaN,NaN,NaN,NaN,200000
31,Fiat Palio 1.2 ELX,2003,50000,Petrol,Individual,Manual,Second Owner,NaN,NaN,NaN,NaN,NaN,70000
78,Tata Indica DLS,2003,70000,Diesel,Individual,Manual,First Owner,NaN,NaN,NaN,NaN,NaN,50000
87,Maruti Swift VDI BSIV W ABS,2015,78000,Diesel,Dealer,Manual,First Owner,NaN,NaN,NaN,NaN,NaN,475000

In [7]:
freq_val =data['seats'].mode()
freq_val

0    5.0
Name: seats, dtype: float64

In [8]:
data1= data.fillna({"seats":freq_val})

data1

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,selling_price
0,Maruti Swift Dzire VDI,2014,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,450000
1,Skoda Rapid 1.5 TDI Ambition,2014,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0,370000
2,Honda City 2017-2020 EXi,2006,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0,158000
3,Hyundai i20 Sportz Diesel,2010,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0,225000
4,Maruti Swift VXI BSIII,2007,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0,130000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,Maruti Zen Estilo LXI BSIII,2009,55500,Petrol,Dealer,Manual,First Owner,18.2 kmpl,998 CC,67.1 bhp,90Nm@ 3500rpm,5.0,175000
95,Hyundai i20 Asta Optional with Sunroof 1.2,2013,61500,Petrol,Dealer,Manual,First Owner,18.5 kmpl,1197 CC,82.85 bhp,113.7Nm@ 4000rpm,5.0,525000
96,Maruti Swift Dzire LDI,2016,150000,Diesel,Individual,Manual,First Owner,26.59 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,600000
97,Hyundai Xcent 1.2 Kappa SX Option AT,2016,72000,Petrol,Dealer,Automatic,First Owner,19.1 kmpl,1197 CC,82 bhp,114Nm@ 4000rpm,5.0,565000
98,Maruti Alto LX BSIII,2008,68000,Petrol,Dealer,Manual,Third Owner,19.7 kmpl,796 CC,46.3 bhp,62Nm@ 3000rpm,5.0,120000

In [11]:
f=data1.isnull().any(axis=1)
data1[f]

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,selling_price
13,Maruti Swift 1.3 VXi,2007,80000,Petrol,Individual,Manual,Second Owner,NaN,NaN,NaN,NaN,NaN,200000
31,Fiat Palio 1.2 ELX,2003,50000,Petrol,Individual,Manual,Second Owner,NaN,NaN,NaN,NaN,NaN,70000
78,Tata Indica DLS,2003,70000,Diesel,Individual,Manual,First Owner,NaN,NaN,NaN,NaN,NaN,50000
87,Maruti Swift VDI BSIV W ABS,2015,78000,Diesel,Dealer,Manual,First Owner,NaN,NaN,NaN,NaN,NaN,475000

In [12]:
f=data1.isnull().any(axis=1)
data1[f]

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,selling_price
13,Maruti Swift 1.3 VXi,2007,80000,Petrol,Individual,Manual,Second Owner,NaN,NaN,NaN,NaN,NaN,200000
31,Fiat Palio 1.2 ELX,2003,50000,Petrol,Individual,Manual,Second Owner,NaN,NaN,NaN,NaN,NaN,70000
78,Tata Indica DLS,2003,70000,Diesel,Individual,Manual,First Owner,NaN,NaN,NaN,NaN,NaN,50000
87,Maruti Swift VDI BSIV W ABS,2015,78000,Diesel,Dealer,Manual,First Owner,NaN,NaN,NaN,NaN,NaN,475000

In [13]:
frequent=data1['torque'].mode()
frequent

0    200Nm@ 1750rpm
Name: torque, dtype: object

In [14]:
data2=data1.fillna({'torque':frequent})
data2

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,selling_price
0,Maruti Swift Dzire VDI,2014,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,450000
1,Skoda Rapid 1.5 TDI Ambition,2014,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0,370000
2,Honda City 2017-2020 EXi,2006,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0,158000
3,Hyundai i20 Sportz Diesel,2010,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0,225000
4,Maruti Swift VXI BSIII,2007,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0,130000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,Maruti Zen Estilo LXI BSIII,2009,55500,Petrol,Dealer,Manual,First Owner,18.2 kmpl,998 CC,67.1 bhp,90Nm@ 3500rpm,5.0,175000
95,Hyundai i20 Asta Optional with Sunroof 1.2,2013,61500,Petrol,Dealer,Manual,First Owner,18.5 kmpl,1197 CC,82.85 bhp,113.7Nm@ 4000rpm,5.0,525000
96,Maruti Swift Dzire LDI,2016,150000,Diesel,Individual,Manual,First Owner,26.59 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,600000
97,Hyundai Xcent 1.2 Kappa SX Option AT,2016,72000,Petrol,Dealer,Automatic,First Owner,19.1 kmpl,1197 CC,82 bhp,114Nm@ 4000rpm,5.0,565000
98,Maruti Alto LX BSIII,2008,68000,Petrol,Dealer,Manual,Third Owner,19.7 kmpl,796 CC,46.3 bhp,62Nm@ 3000rpm,5.0,120000

In [15]:
frequent_val=data2['max_power'].mode()
frequent_val

0    74 bhp
Name: max_power, dtype: object

In [16]:
data3=data2.fillna({'max_power':frequent_val})
data3

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,selling_price
0,Maruti Swift Dzire VDI,2014,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,450000
1,Skoda Rapid 1.5 TDI Ambition,2014,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0,370000
2,Honda City 2017-2020 EXi,2006,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0,158000
3,Hyundai i20 Sportz Diesel,2010,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0,225000
4,Maruti Swift VXI BSIII,2007,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0,130000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,Maruti Zen Estilo LXI BSIII,2009,55500,Petrol,Dealer,Manual,First Owner,18.2 kmpl,998 CC,67.1 bhp,90Nm@ 3500rpm,5.0,175000
95,Hyundai i20 Asta Optional with Sunroof 1.2,2013,61500,Petrol,Dealer,Manual,First Owner,18.5 kmpl,1197 CC,82.85 bhp,113.7Nm@ 4000rpm,5.0,525000
96,Maruti Swift Dzire LDI,2016,150000,Diesel,Individual,Manual,First Owner,26.59 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,600000
97,Hyundai Xcent 1.2 Kappa SX Option AT,2016,72000,Petrol,Dealer,Automatic,First Owner,19.1 kmpl,1197 CC,82 bhp,114Nm@ 4000rpm,5.0,565000
98,Maruti Alto LX BSIII,2008,68000,Petrol,Dealer,Manual,Third Owner,19.7 kmpl,796 CC,46.3 bhp,62Nm@ 3000rpm,5.0,120000

In [17]:
freq_value=data3['engine'].mode()
freq_value

0    1248 CC
Name: engine, dtype: object

In [18]:
data4=data3.fillna({'engine':freq_value})
data4

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,selling_price
0,Maruti Swift Dzire VDI,2014,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,450000
1,Skoda Rapid 1.5 TDI Ambition,2014,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0,370000
2,Honda City 2017-2020 EXi,2006,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0,158000
3,Hyundai i20 Sportz Diesel,2010,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0,225000
4,Maruti Swift VXI BSIII,2007,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0,130000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,Maruti Zen Estilo LXI BSIII,2009,55500,Petrol,Dealer,Manual,First Owner,18.2 kmpl,998 CC,67.1 bhp,90Nm@ 3500rpm,5.0,175000
95,Hyundai i20 Asta Optional with Sunroof 1.2,2013,61500,Petrol,Dealer,Manual,First Owner,18.5 kmpl,1197 CC,82.85 bhp,113.7Nm@ 4000rpm,5.0,525000
96,Maruti Swift Dzire LDI,2016,150000,Diesel,Individual,Manual,First Owner,26.59 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,600000
97,Hyundai Xcent 1.2 Kappa SX Option AT,2016,72000,Petrol,Dealer,Automatic,First Owner,19.1 kmpl,1197 CC,82 bhp,114Nm@ 4000rpm,5.0,565000
98,Maruti Alto LX BSIII,2008,68000,Petrol,Dealer,Manual,Third Owner,19.7 kmpl,796 CC,46.3 bhp,62Nm@ 3000rpm,5.0,120000

In [19]:
d=data4.isnull().any(axis=1)
data4[d]

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,selling_price
13,Maruti Swift 1.3 VXi,2007,80000,Petrol,Individual,Manual,Second Owner,NaN,NaN,NaN,NaN,NaN,200000
31,Fiat Palio 1.2 ELX,2003,50000,Petrol,Individual,Manual,Second Owner,NaN,NaN,NaN,NaN,NaN,70000
78,Tata Indica DLS,2003,70000,Diesel,Individual,Manual,First Owner,NaN,NaN,NaN,NaN,NaN,50000
87,Maruti Swift VDI BSIV W ABS,2015,78000,Diesel,Dealer,Manual,First Owner,NaN,NaN,NaN,NaN,NaN,475000

In [20]:
frequent_value=data4['mileage'].mode()
frequent_value

0    24.3 kmpl
Name: mileage, dtype: object

In [21]:
data5=data4.fillna({'mileage':frequent_value})
data5

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,selling_price
0,Maruti Swift Dzire VDI,2014,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,450000
1,Skoda Rapid 1.5 TDI Ambition,2014,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0,370000
2,Honda City 2017-2020 EXi,2006,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0,158000
3,Hyundai i20 Sportz Diesel,2010,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0,225000
4,Maruti Swift VXI BSIII,2007,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0,130000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,Maruti Zen Estilo LXI BSIII,2009,55500,Petrol,Dealer,Manual,First Owner,18.2 kmpl,998 CC,67.1 bhp,90Nm@ 3500rpm,5.0,175000
95,Hyundai i20 Asta Optional with Sunroof 1.2,2013,61500,Petrol,Dealer,Manual,First Owner,18.5 kmpl,1197 CC,82.85 bhp,113.7Nm@ 4000rpm,5.0,525000
96,Maruti Swift Dzire LDI,2016,150000,Diesel,Individual,Manual,First Owner,26.59 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,600000
97,Hyundai Xcent 1.2 Kappa SX Option AT,2016,72000,Petrol,Dealer,Automatic,First Owner,19.1 kmpl,1197 CC,82 bhp,114Nm@ 4000rpm,5.0,565000
98,Maruti Alto LX BSIII,2008,68000,Petrol,Dealer,Manual,Third Owner,19.7 kmpl,796 CC,46.3 bhp,62Nm@ 3000rpm,5.0,120000

In [22]:
data['transmission'].unique()

array(['Manual', 'Automatic'], dtype=object)

In [23]:
data_encoded=data5.replace({
    'transmission':{'Manual':0,'Automatic':1}
})
data_encoded

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,selling_price
0,Maruti Swift Dzire VDI,2014,145500,Diesel,Individual,0,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,450000
1,Skoda Rapid 1.5 TDI Ambition,2014,120000,Diesel,Individual,0,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0,370000
2,Honda City 2017-2020 EXi,2006,140000,Petrol,Individual,0,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0,158000
3,Hyundai i20 Sportz Diesel,2010,127000,Diesel,Individual,0,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0,225000
4,Maruti Swift VXI BSIII,2007,120000,Petrol,Individual,0,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0,130000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,Maruti Zen Estilo LXI BSIII,2009,55500,Petrol,Dealer,0,First Owner,18.2 kmpl,998 CC,67.1 bhp,90Nm@ 3500rpm,5.0,175000
95,Hyundai i20 Asta Optional with Sunroof 1.2,2013,61500,Petrol,Dealer,0,First Owner,18.5 kmpl,1197 CC,82.85 bhp,113.7Nm@ 4000rpm,5.0,525000
96,Maruti Swift Dzire LDI,2016,150000,Diesel,Individual,0,First Owner,26.59 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,600000
97,Hyundai Xcent 1.2 Kappa SX Option AT,2016,72000,Petrol,Dealer,1,First Owner,19.1 kmpl,1197 CC,82 bhp,114Nm@ 4000rpm,5.0,565000
98,Maruti Alto LX BSIII,2008,68000,Petrol,Dealer,0,Third Owner,19.7 kmpl,796 CC,46.3 bhp,62Nm@ 3000rpm,5.0,120000

In [24]:
data5['seller_type'].unique()

array(['Individual', 'Dealer'], dtype=object)

In [25]:
data_encoded1=data_encoded.replace({
    "seller_type":{"Individual":0,"Dealer":1,"Trustmark Dealer":2}
    
})
data_encoded1

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,selling_price
0,Maruti Swift Dzire VDI,2014,145500,Diesel,0,0,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,450000
1,Skoda Rapid 1.5 TDI Ambition,2014,120000,Diesel,0,0,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0,370000
2,Honda City 2017-2020 EXi,2006,140000,Petrol,0,0,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0,158000
3,Hyundai i20 Sportz Diesel,2010,127000,Diesel,0,0,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0,225000
4,Maruti Swift VXI BSIII,2007,120000,Petrol,0,0,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0,130000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,Maruti Zen Estilo LXI BSIII,2009,55500,Petrol,1,0,First Owner,18.2 kmpl,998 CC,67.1 bhp,90Nm@ 3500rpm,5.0,175000
95,Hyundai i20 Asta Optional with Sunroof 1.2,2013,61500,Petrol,1,0,First Owner,18.5 kmpl,1197 CC,82.85 bhp,113.7Nm@ 4000rpm,5.0,525000
96,Maruti Swift Dzire LDI,2016,150000,Diesel,0,0,First Owner,26.59 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,600000
97,Hyundai Xcent 1.2 Kappa SX Option AT,2016,72000,Petrol,1,1,First Owner,19.1 kmpl,1197 CC,82 bhp,114Nm@ 4000rpm,5.0,565000
98,Maruti Alto LX BSIII,2008,68000,Petrol,1,0,Third Owner,19.7 kmpl,796 CC,46.3 bhp,62Nm@ 3000rpm,5.0,120000

In [26]:
data["fuel"].unique()

array(['Diesel', 'Petrol', 'LPG', 'CNG'], dtype=object)

In [27]:
data_encoded2=data_encoded1.replace({
    "fuel":{'Diesel':0,'Petrol':1,'LPG':2,'CNG':3}
})
data_encoded2

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,selling_price
0,Maruti Swift Dzire VDI,2014,145500,0,0,0,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,450000
1,Skoda Rapid 1.5 TDI Ambition,2014,120000,0,0,0,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0,370000
2,Honda City 2017-2020 EXi,2006,140000,1,0,0,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0,158000
3,Hyundai i20 Sportz Diesel,2010,127000,0,0,0,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0,225000
4,Maruti Swift VXI BSIII,2007,120000,1,0,0,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0,130000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,Maruti Zen Estilo LXI BSIII,2009,55500,1,1,0,First Owner,18.2 kmpl,998 CC,67.1 bhp,90Nm@ 3500rpm,5.0,175000
95,Hyundai i20 Asta Optional with Sunroof 1.2,2013,61500,1,1,0,First Owner,18.5 kmpl,1197 CC,82.85 bhp,113.7Nm@ 4000rpm,5.0,525000
96,Maruti Swift Dzire LDI,2016,150000,0,0,0,First Owner,26.59 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,600000
97,Hyundai Xcent 1.2 Kappa SX Option AT,2016,72000,1,1,1,First Owner,19.1 kmpl,1197 CC,82 bhp,114Nm@ 4000rpm,5.0,565000
98,Maruti Alto LX BSIII,2008,68000,1,1,0,Third Owner,19.7 kmpl,796 CC,46.3 bhp,62Nm@ 3000rpm,5.0,120000

In [28]:
data["owner"].unique()

array(['First Owner', 'Second Owner', 'Third Owner'], dtype=object)

In [29]:
data_encoded3=data_encoded2.replace({
    "owner":{"Test Drive Car":0,"First Owner":1,"Second Owner":2,"Third Owner":3,"Fourth & Above Owner":4}
})
data_encoded3

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,selling_price
0,Maruti Swift Dzire VDI,2014,145500,0,0,0,1,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,450000
1,Skoda Rapid 1.5 TDI Ambition,2014,120000,0,0,0,2,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0,370000
2,Honda City 2017-2020 EXi,2006,140000,1,0,0,3,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0,158000
3,Hyundai i20 Sportz Diesel,2010,127000,0,0,0,1,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0,225000
4,Maruti Swift VXI BSIII,2007,120000,1,0,0,1,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0,130000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,Maruti Zen Estilo LXI BSIII,2009,55500,1,1,0,1,18.2 kmpl,998 CC,67.1 bhp,90Nm@ 3500rpm,5.0,175000
95,Hyundai i20 Asta Optional with Sunroof 1.2,2013,61500,1,1,0,1,18.5 kmpl,1197 CC,82.85 bhp,113.7Nm@ 4000rpm,5.0,525000
96,Maruti Swift Dzire LDI,2016,150000,0,0,0,1,26.59 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0,600000
97,Hyundai Xcent 1.2 Kappa SX Option AT,2016,72000,1,1,1,1,19.1 kmpl,1197 CC,82 bhp,114Nm@ 4000rpm,5.0,565000
98,Maruti Alto LX BSIII,2008,68000,1,1,0,3,19.7 kmpl,796 CC,46.3 bhp,62Nm@ 3000rpm,5.0,120000

In [30]:
data["name"].unique()

array(['Maruti Swift Dzire VDI', 'Skoda Rapid 1.5 TDI Ambition',
       'Honda City 2017-2020 EXi', 'Hyundai i20 Sportz Diesel',
       'Maruti Swift VXI BSIII', 'Hyundai Xcent 1.2 VTVT E Plus',
       'Maruti Wagon R LXI DUO BSIII', 'Maruti 800 DX BSII',
       'Toyota Etios VXD', 'Ford Figo Diesel Celebration Edition',
       'Renault Duster 110PS Diesel RxL', 'Maruti Zen LX',
       'Maruti Swift Dzire VDi', 'Maruti Swift 1.3 VXi',
       'Maruti Wagon R LXI Minor', 'Mahindra KUV 100 mFALCON G80 K8 5str',
       'Maruti Ertiga SHVS VDI', 'Hyundai i20 1.4 CRDi Asta',
       'Maruti Alto LX', 'Hyundai i20 2015-2017 Asta 1.4 CRDi',
       'Mahindra Verito 1.5 D4 BSIII', 'Honda WR-V i-DTEC VX',
       'Maruti Swift Dzire ZDI', 'Maruti SX4 ZDI',
       'Tata Tigor 2017-2020 XZ', 'Maruti Baleno Delta 1.2',
       'Maruti Alto 800 LXI', 'Chevrolet Enjoy TCDi LTZ 7 Seater',
       'Maruti Omni E MPI STD BS IV', 'Maruti Vitara Brezza LDi Option',
       'Fiat Palio 1.2 ELX', 'Maruti Omni 8 Seater BSIV',
       'Hyundai i20 1.2 Asta Dual Tone', 'Maruti Vitara Brezza LDi',
       'Maruti Alto 800 CNG LXI Optional', 'Maruti Alto K10 VXI Airbag',
       'Hyundai Verna VTVT 1.6 SX Option', 'Datsun GO D',
       'Tata Safari DICOR 2.2 LX 4x2', 'Maruti 800 Std',
       'Jeep Compass 1.4 Limited Plus BSIV', 'Honda City i VTEC VX',
       'Honda City V MT', 'Maruti Swift Dzire VXi AT',
       'Maruti Vitara Brezza VDi', 'Maruti Alto K10 VXI',
       'Toyota Fortuner 4x4 MT',
       'Toyota Innova 2.5 G (Diesel) 7 Seater BS IV',
       'Mercedes-Benz B Class B180', 'Honda Amaze S Diesel',
       'Mitsubishi Pajero Sport 4X4', 'Honda City i DTEC S',
       'Maruti Ciaz Zeta', 'Honda Jazz VX Diesel',
       'Toyota Innova Crysta 2.8 ZX AT BSIV',
       'Toyota Innova 2.5 G (Diesel) 7 Seater',
       'Audi A6 2.0 TDI Technology', 'Toyota Corolla Altis 1.8 VL CVT',
       'Audi A6 2.0 TDI  Design Edition',
       'Mercedes-Benz New C-Class 220 CDI AT',
       'Tata Manza ELAN Quadrajet BS IV', 'Hyundai i10 Magna',
       'Hyundai i20 Asta 1.4 CRDi', 'Ford Figo 1.2P Titanium MT',
       'Volkswagen Ameo 1.5 TDI Highline 16 Alloy',
       'Honda City i DTEC VX', 'Maruti Wagon R AMT VXI',
       'Volkswagen Ameo 1.5 TDI Comfortline',
       'Maruti Vitara Brezza ZDi Plus AMT', 'Maruti Swift VDI Deca',
       'Maruti Swift Star VDI', 'Maruti Ertiga ZXI', 'Tata Indica DLS',
       'Volkswagen Vento Diesel Highline',
       'Toyota Innova 2.5 VX (Diesel) 8 Seater',
       'Ford EcoSport 1.5 TDCi Titanium Plus BSIV',
       'BMW X1 sDrive20i xLine', 'Maruti Celerio ZXI MT BSIV',
       'Datsun GO A Petrol', 'Maruti Alto 800 VXI BSIV',
       'Maruti Alto 800 LXI BSIV', 'Maruti Swift VDI BSIV W ABS',
       'Hyundai i10 Era 1.1', 'Maruti Wagon R LXI LPG BSIV',
       'Volkswagen Polo 1.2 MPI Comfortline', 'Hyundai i10 Magna 1.1L',
       'Volkswagen Vento Petrol Highline', 'Maruti Zen Estilo LXI BSIII',
       'Hyundai i20 Asta Optional with Sunroof 1.2',
       'Maruti Swift Dzire LDI', 'Hyundai Xcent 1.2 Kappa SX Option AT',
       'Maruti Alto LX BSIII'], dtype=object)

In [31]:
data_encoded4=pd.get_dummies(data_encoded3)
data_encoded4

,year,km_driven,fuel,seller_type,transmission,owner,seats,selling_price,name_Audi A6 2.0 TDI Design Edition,name_Audi A6 2.0 TDI Technology,...,torque_6.1kgm@ 3000rpm,torque_60Nm@ 3500rpm,torque_62Nm@ 3000rpm,torque_69Nm@ 3500rpm,"torque_7.8@ 4,500(kgm@ rpm)",torque_77Nm@ 3500rpm,torque_78Nm@ 4500rpm,torque_84Nm@ 3500rpm,torque_90Nm@ 3500rpm,torque_99.04Nm@ 4500rpm
0,2014,145500,0,0,0,1,5.0,450000,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2014,120000,0,0,0,2,5.0,370000,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2006,140000,1,0,0,3,5.0,158000,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2010,127000,0,0,0,1,5.0,225000,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2007,120000,1,0,0,1,5.0,130000,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,2009,55500,1,1,0,1,5.0,175000,0,0,...,0,0,0,0,0,0,0,0,1,0
95,2013,61500,1,1,0,1,5.0,525000,0,0,...,0,0,0,0,0,0,0,0,0,0
96,2016,150000,0,0,0,1,5.0,600000,0,0,...,0,0,0,0,0,0,0,0,0,0
97,2016,72000,1,1,1,1,5.0,565000,0,0,...,0,0,0,0,0,0,0,0,0,0
98,2008,68000,1,1,0,3,5.0,120000,0,0,...,0,0,1,0,0,0,0,0,0,0

In [32]:
data_encoded4.isnull()

,year,km_driven,fuel,seller_type,transmission,owner,seats,selling_price,name_Audi A6 2.0 TDI Design Edition,name_Audi A6 2.0 TDI Technology,...,torque_6.1kgm@ 3000rpm,torque_60Nm@ 3500rpm,torque_62Nm@ 3000rpm,torque_69Nm@ 3500rpm,"torque_7.8@ 4,500(kgm@ rpm)",torque_77Nm@ 3500rpm,torque_78Nm@ 4500rpm,torque_84Nm@ 3500rpm,torque_90Nm@ 3500rpm,torque_99.04Nm@ 4500rpm
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
95,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [33]:
f=data_encoded4.isnull().any(axis=1)
data[f]

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,selling_price
13,Maruti Swift 1.3 VXi,2007,80000,Petrol,Individual,Manual,Second Owner,NaN,NaN,NaN,NaN,NaN,200000
31,Fiat Palio 1.2 ELX,2003,50000,Petrol,Individual,Manual,Second Owner,NaN,NaN,NaN,NaN,NaN,70000
78,Tata Indica DLS,2003,70000,Diesel,Individual,Manual,First Owner,NaN,NaN,NaN,NaN,NaN,50000
87,Maruti Swift VDI BSIV W ABS,2015,78000,Diesel,Dealer,Manual,First Owner,NaN,NaN,NaN,NaN,NaN,475000

ml algorithms
1-logistic regression

import libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib as plt

#import dataset

In [ ]:

x=data_encoded4.iloc[:,:-1].values
y=data_encoded4.iloc[:,-1].values

spliting data

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size=0.20,random_state=0)

In [ ]:
print(x_train)

In [ ]:
print(x_test)

In [ ]:
print(y_train)

In [ ]:
print(y_test)

#feature scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test =sc.transform(x_test)

In [ ]:
print(x_train)

In [ ]:
print(x_test)

# training the logistic regression model on the dataset

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier= LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)